// Autogenerated name suggestions for first-seen devices -- see README.md
// "Autogenerated name suggestions" for the full rule.

export function slugify(input) {
  return input
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function suffixFromIp(ipv4) {
  const parts = ipv4.split(".");
  if (parts.length !== 4) return null;
  return parts[3];
}

export function suffixFromCounter(existingNames, base) {
  if (!existingNames.includes(base)) return "";
  let n = 2;
  while (existingNames.includes(`${base}${n}`)) n++;
  return String(n);
}

const IP_REACHABLE_TRANSPORTS = new Set(["mdns", "dhcp"]);

// Composes the three above: IP-reachable devices get the last octet as a
// suffix, everything else falls back to the shortest unused counter.
export function suggestName({ hostname, address, transport, existingNames }) {
  const base = slugify(hostname || transport);

  if (IP_REACHABLE_TRANSPORTS.has(transport)) {
    const octet = suffixFromIp(address);
    if (octet) return `${base}${octet}`;
  }

  return `${base}${suffixFromCounter(existingNames, base)}`;
}
